# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T5IjQiTyOjcSeAc6skN_iZjAiTn-sMYO
"""

import matplotlib.pyplot as plt
import numpy as np
time = np.linspace(0, 2, 500)
heartbeat = np.sin(2 * np.pi * 2 * time) * np.exp(-3 * time)
heartbeat[heartbeat < 0] = 0
plt.figure(figsize=(10, 5))
plt.plot(time, heartbeat, label="Yurak Urishi")
plt.title("Yurak Urishining Modeli")
plt.xlabel("Vaqt (soniya)")
plt.ylabel("Amplitude")
plt.grid(True)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([3,8,1,10])
plt.plot(y,'o:r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6])
y=np.array([0,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([3,8,1,10])
plt.plot(y,marker='o',ms=20 )
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([3,8,1,10])
plt.plot(y,marker='o',ms=20, mec='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1= np.array([0,10,20,30,40,50,60,70,80,90,100] )
y1= np.array([30,55,25,70,40,50,30,60,30,70,60] )
x2= np.array([30,55,25,70,40,50,30,60,30,70,60] )
y2= np.array([ 0,10,20,30,40,50,60,70,80,90,100] )
plt.plot (x1,x2 ,y1,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([0,1,2,3,4,5])
y = np.array([0,8,12,20,26,38])
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([0,1,2,3,4,5])
y = np.array([0,2,8,1,14,7])
plt.scatter(x,y,color='red')
x = np.array([12,6,8,11,8,3])
y = np.array([5,6,3,7,17,19])
plt.scatter(x,y,color='green')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0,1,2,3,4,5])
y = np.array([0,2,8,1,14,7])
mycolor=['red', 'green', 'purple', 'lime', 'aqua',' yellow']

plt.scatter(x,y,color= mycolor )

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0,1,2,3,4,5])
y = np.array([0,2,8,1,14,7])
mycolor=['red', 'green','purple', 'lime','aqua','yellow']
size=[10,60,120,80,20,190]
plt.scatter(x,y,color= mycolor, s=size )
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array(['A','B','C','D'])
y = np.array([3,8,1,10])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array(['A','B','C','D'])
y = np.array([3,8,1,10])
plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x= np.array(['A','B','C','D'])
y = np.array([3,8,1,10])
plt.bar(x,y,width=0.1)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([35,25,25,15])
plt. pie(y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([35,25,25,15])
mylabels = ["Apples", "Bananas","Cherries", "Dates"]
plt.pie(y, labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([35,25,25,15])
mylabels = ["Apples", "Bananas",
"Cherries", "Dates"]
plt.pie(y, labels=mylabels,startangle=90)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([35,25,25,15])
mylabels = ["Apples", "Bananas","Cherries", "Dates"]
plt.pie(y, labels=mylabels,startangle=90)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries","Dates"]
myexplode = [0.2, 0, 0, 0]
plt.pie(y, labels=mylabels,
startangle=90,explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array ([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries","Dates"]
myexplode = [0.2, 0, 0, 0]
plt.pie(y, labels=mylabels, startangle=90,
explode=myexplode, shadow=True)
plt.show()



import matplotlib.pyplot as plt
import numpy as np
x = np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries",
"Dates"]
mycolors = ["black", "hotpink", "b", "#4CAF50"]
myexplode = [0.2, 0, 0, 0]
plt.pie(y, labels=mylabels, startangle=90,
explode=myexplode, colors= mycolors)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries","Dates"]
plt.pie(y, labels=mylabels)
plt.legend()
plt.show()